import pyautogui
import time

# Set the text you want to send
text_to_send = "this is a Automated message generated by BOT"

# Set the number of times you want to send the text
num_times = 5

# Delay before starting to send text
time.sleep(1)  # Wait for 5 seconds before starting

for _ in range(num_times):
    pyautogui.write(text_to_send)
    pyautogui.press("enter")
    time.sleep(1)  # Delay between each message

print(f"Sent '{text_to_send}' {num_times} times.")
